pipeline {
  agent any
  tools {
    maven 'maven'   // the tool you just set to 3.9.9
    jdk   'java'    // your configured JDK
  }
  options { skipStagesAfterUnstable() }
  stages {
    stage('Build') {
      steps {
        sh 'mvn -v' // should print 3.9.9
        sh 'mvn -B -DskipTests clean package'
      }
    }
    stage('Test') {
      steps { sh 'mvn test' }
      post { always { junit 'target/surefire-reports/*.xml' } }
    }
    stage('Deliver') {
      steps { sh './jenkins/scripts/deliver.sh' }
    }
  }
}
